<a href="https://colab.research.google.com/github/HiteshPandharkar/Algorithms-From-Scratch/blob/main/LinReg_SGD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_boston

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')

In [ ]:
data = load_boston()

x = data['data'][: 450]
y = data['target'][: 450]

x_test = data['data'][450: ]
y_test = data['target'][450: ]

In [ ]:
class LinearRegression :

  def __init__(self, learning_rate, epochs) :
    self.coeff = np.array([])
    self.intercept = 0
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.error = np.array([])

  def fit(self, x, y) :

    ones = np.ones(len(x)).reshape(-1, 1)
    x = np.concatenate((ones, x), axis=1)

    self.theta = np.zeros(len(data['feature_names'])+1)

    #y_hat = np.array([np.mean(y) for i in range(len(y))])

    a = np.concatenate((x, y.reshape(-1, 1)), axis=1)

    for i in range(self.epochs) :
      np.random.shuffle(a)
      X = a[:, :-1]
      Y = a[:, -1]
      for j in range(len(X)) :

        y_hat = np.dot(X[j], self.theta)

        error = (y_hat-Y[j])*X[j]
        rate = self.learning_rate/len(X)

        self.theta = self.theta-(rate*error)
      if i == self.epochs-1 :
        self.coeff = self.theta[1:]
        self.intercept = self.theta[0]


  def predict(self, x_test) :

    ones = np.ones(len(x_test)).reshape(len(x_test), 1)
    x_test = np.concatenate((ones, x_test), axis=1)

    y_pred = np.dot(x_test, self.theta)

    return y_pred


In [ ]:
mode = LinearRegression(learning_rate=.00001, epochs=10000)
mode.fit(x, y)

In [ ]:
mode.predict(x_test)

array([ 9.13926772, 22.59905933, 23.15683278, 24.38367168,  8.23637005,
        9.80395551,  7.50046809,  7.64582537, 18.66277262, 24.50184318,
       19.1305812 , 25.27610581, 25.04882801, 28.89149191, 23.44436394,
       18.6647156 ,  9.11721417, 18.16873293, 18.20186581, 20.40710242,
       23.47215895, 26.99742521, 24.06641645, 24.86875998, 20.92634852,
       15.12169295, 22.76194596, 14.84232753, 22.34126651, 25.01624173,
       25.56977808, 29.30127319, 30.37476231, 22.89437494, 20.03202741,
       24.16468896, 23.71824973, 23.26753848, 22.31122266, 16.33693121,
       10.61718956, 23.11684206, 25.370049  , 21.75617279, 19.27187645,
       14.19823845, 16.45569463, 22.04804524, 22.49952625, 21.42991604,
       23.04841097, 25.41368372, 26.6975096 , 31.57013168, 30.47215936,
       28.08783763])

In [ ]:
mode.coeff

array([-0.10049862,  0.10369   , -0.03996385,  0.03257416,  0.01743279,
        0.5334846 ,  0.11616638,  0.00293698,  0.02684223,  0.00503705,
        0.30097615,  0.03651975, -0.80136315])

In [ ]:
mode.intercept

0.04646629983744112

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x, y)

model.predict(x_test)

array([16.93342847, 20.02045317, 19.1112216 , 23.22511636, 15.67053396,
       16.16461608, 12.94871109, 13.10761941, 17.6319346 , 19.03284579,
       19.59255106, 20.77045231, 20.32972514, 23.18351143, 20.68319592,
       18.0040013 , 14.64560774, 17.27282806, 17.13977735, 18.68551487,
       20.60338383, 23.55507294, 22.87962378, 26.04862777, 16.72644386,
       16.36479094, 21.00709718, 11.6612751 , 19.64804461, 22.3241981 ,
       23.86289088, 27.72777956, 29.28276029, 21.24700039, 19.56624682,
       22.57946369, 20.10876414, 21.5593847 , 10.86871125,  7.10200759,
        2.34094092, 12.89668156, 15.06381197, 20.29041819, 20.14661342,
       16.17245839, 13.60940848, 18.92607466, 21.08818519, 18.21312845,
       20.37078103, 23.66927765, 22.53513428, 28.11477396, 26.56785292,
       22.58084479])

In [ ]:
model.coef_

array([-1.12706397e-01,  4.84679322e-02,  3.51619982e-02,  2.43036682e+00,
       -1.71555914e+01,  3.92937664e+00,  1.05952560e-02, -1.40598405e+00,
        3.72316544e-01, -1.54340774e-02, -9.03360601e-01,  9.74047349e-03,
       -5.51630479e-01])

In [ ]:
model.intercept_

34.26122511499132